window.armor = [
    {
        id: 2001,
        name: "Armadura de Couro",
        type: "armor",
        defense: 3,
        value: 20,
        icon: "🛡️",
        description: "Armadura leve feita de couro resistente",
        requiredLevel: 1,
        shopPrice: 200
    },
    {
        id: 2002,
        name: "Cota de Malha",
        type: "armor",
        defense: 6,
        value: 60,
        icon: "🔗",
        description: "Feita de anéis metálicos entrelaçados",
        requiredLevel: 4,
        shopPrice: 600
    },
    {
        id: 2003,
        name: "Armadura de Aço",
        type: "armor",
        defense: 10,
        value: 850,
        icon: "⚙️",
        description: "Proteção robusta usada por cavaleiros",
        requiredLevel: 8,
        shopPrice: 8500
    },
    {
        id: 2004,
        name: "Peitoral Flamejante",
        type: "armor",
        defense: 15,
        value: 1300,
        icon: "🔥",
        description: "Protege contra ataques de fogo e físicos",
        requiredLevel: 13,
        shopPrice: 13000
    },
    {
        id: 2005,
        name: "Escamas de Dragão",
        type: "armor",
        defense: 22,
        value: 3200,
        icon: "🐉",
        description: "Feita com escamas reais de dragão",
        requiredLevel: 17,
        shopPrice: 32000
    },
    {
        id: 2006,
        name: "Armadura do Guardião",
        type: "armor",
        defense: 30,
        value: 7000,
        icon: "🛡️",
        description: "Usada por guerreiros lendários",
        requiredLevel: 22,
        shopPrice: 70000
    },
    {
        id: 2007,
        name: "Manto do Inverno Eterno",
        type: "armor",
        defense: 50,
        value: 15000,
        icon: "❄️",
        description: "Bloqueia ataques físicos e mágicos com gelo",
        requiredLevel: 26,
        shopPrice: 150000
    },
    {
        id: 2008,
        name: "Armadura Sagrada",
        type: "armor",
        defense: 65,
        value: 30000,
        icon: "🕊️",
        description: "Proteção divina contra forças do mal",
        requiredLevel: 30,
        shopPrice: 300000
    },
    {
        id: 2009,
        name: "Capa Estelar",
        type: "armor",
        defense: 85,
        value: 120000,
        icon: "🌌",
        description: "Oferece resistência ao caos e ao cosmos",
        requiredLevel: 33,
        shopPrice: 450000
    },
    {
        id: 2010,
        name: "Platina Cósmica",
        type: "armor",
        defense: 120,
        value: 250000,
        icon: "🪐",
        description: "Feita com minério de asteróide. Quase impenetrável.",
        requiredLevel: 36,
        shopPrice: 650000
    },
    {
        id: 2011,
        name: "Capa de Folhas",
        type: "armor",
        defense: 2,
        value: 100,
        icon: "🍃",
        description: "Leve e camuflada, ideal para floresta.",
        requiredLevel: 1,
        shopPrice: 100
    },
    {
        id: 2012,
         name: "Pelagem Glacial",
        type: "armor",
        defense: 50,
        value: 20000,
        icon: "🧊",
        description: "Isola contra frio extremo.",
        requiredLevel: 30,
        shopPrice: 200000
    },
    {
        id: 2013,
        name: "Capa da Nevasca",
        type: "armor",
        defense: 60,
        value: 28000,
        icon: "❄️",
        description: "Pode reduzir a velocidade do atacante.",
        requiredLevel: 36,
        shopPrice: 280000
    },
    {
        id: 2014,
        name: "Armadura do Abismo",
        type: "armor",
        defense: 85,
        value: 50000,
        icon: "🌊",
        description: "Excelente proteção em ambientes submersos.",
        requiredLevel: 37,
        shopPrice: 500000
    },
    {
        id: 2015,
        name: "Manto das Profundezas",
        type: "armor",
        defense: 100,
        value: 60000,
        icon: "🧜",
        description: "Reduz chance de acerto crítico.",
        requiredLevel: 40,
        shopPrice: 600000
    },
    {
        id: 2016,
        name: "Armadura Infernal",
        type: "armor",
        defense: 130,
        value: 85000,
        icon: "😈",
        description: "Protege contra dano demoníaco.",
        requiredLevel: 45,
        shopPrice: 850000
    },
    {
        id: 2017,
        name: "Carapaça do Tormento",
        type: "armor",
        defense: 150,
        value: 100000,
        icon: "🔥",
        description: "Reduz dano contínuo.",
        requiredLevel: 47,
        shopPrice: 1000000
    },
    {
        id: 2018,
        name: "Armadura Sagrada",
        type: "armor",
        defense: 180,
        value: 120000,
        icon: "☀️",
        description: "Purifica efeitos negativos.",
        requiredLevel: 50,
        shopPrice: 1800000
    },
    {
        id: 2019,
        name: "Túnica do Serafim",
        type: "armor",
        defense: 200,
        value: 160000,
        icon: "🪽",
        description: "Melhora regeneração.",
        requiredLevel: 52,
        shopPrice: 2600000
    },
    {
        id: 2020,
        name: "Armadura Estelar",
        type: "armor",
        defense: 250,
        value: 300000,
        icon: "✨",
        description: "Aumenta resistência a todos os elementos.",
        requiredLevel: 55,
        shopPrice: 5000000
    },
    {
        id: 2021,
        name: "Vestes do Infinito",
        type: "armor",
        defense: 320,
        value: 450000,
        icon: "🌌",
        description: "Concede escudo cósmico periódico.",
        requiredLevel: 150,
        shopPrice: 10500000
    },
];
